name: Validar aplicación

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  web-build:
    name: Compilar React y TypeScript
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Preparar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Compilar aplicación
        run: npm run build
